Feat/HDF-85 Update pool rewards
HaloDAO/pool-worker pull request #1
Opened 2021-04-06 10:02 UTC by mystbrent

## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-85)

## How To Test

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-09 07:10 UTC, ctverceles requested changes
@mystbrent looking good! working on kovan as discussed. these 2 txs calling the 2 functions `updateAMMRewardsPool` https://kovan.etherscan.io/tx/0xc55353abe4ef0ea39e16bba763c0a16d1b8fb30f5c2834ce2807e4ee066ab674 and `updateMinterRewardsPool` https://kovan.etherscan.io/tx/0x48951782f78b82be808e8eb7551183f7d1599ad32682dec728a65067decb916f are working. 

Just some things to look into:
- [ ] fix nonce error that happens when running `npm start` on local
- [ ] use git submodule for the `halo-rewards` repo "import"
- [ ] derive the signer account from the `WALLET_MNEMONIC` so we don't need to list the `WALLET_PRIVATE_KEY`
- [ ] Add postinstall npm script to `package.json` to auto install `halo-rewards` submodule deps

2021-04-10 04:31 UTC, tracyarciaga requested changes

2021-04-10 04:31 UTC, tracyarciaga commented on .gitmodules
> +	url = git@github.com:HaloDAO/halo-rewards.git
Please change url = https://github.com/HaloDAO/halo-rewards.git so that it uses https instead of ssh.
I think HTTPS  is the default authentication protocol in github,  unless you are all  using SSH.

2021-04-14 05:11 UTC, mystbrent commented
Resolution for this PR addressed here: 
https://github.com/HaloDAO/pool-worker/pull/2

2021-04-14 08:37 UTC, ctverceles commented
Ok working now locally for me and on kovan https://kovan.etherscan.io/tx/0xea0ce307f3358979f1d1289c8a6627cdcdaea6fe4b3bcce7fec46b3d1f743b1a, https://kovan.etherscan.io/tx/0x2cb7f57242c64d9ef4e23388a196678b2590cf57c9e8219ebcdd9ce2db24b650

2021-04-14 08:38 UTC, ctverceles approved these changes

2021-04-14 08:44 UTC, merged