Refactor/HDF-96 rewards git submodule
HaloDAO/pool-worker pull request #2
Opened 2021-04-09 10:35 UTC by mystbrent

## Description of Changes

Before this update, the repository explicitly includes halo-reward contracts to the source code to instantiate the Rewards contract. This can be improved by using git submodules to easily reference the halo-rewards contracts to its github repository counterpart.

Added changes also include:

[x] Fix nonce error that happens when running `npm start` on local (Done by giving different cron schedules to tasks)
[x] Add postinstall npm script to package.json to auto install halo-rewards submodule deps
[x] Make use of typescript path module aliases when importing halo-rewards repo to source code

With regards to deriving the signer account from only mnemonic option, I think it limits the option for the worker runner to only one option of using mnemonic. This update also includes resolving that issue by prioritizing the requirement of private key first before mnemonic. This way local tests can easily be done without having to do much effort.

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-96)

## How To Test

### Developer Checklist:

- [x] I have followed the guidelines in our Contributing document
- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
- [x] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally
- [x] I have formatted my code using format document in VSCode

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-10 05:24 UTC, bitcoinbrisbane commented on src/tasks/UpdateAMMReward.ts
> +	Rewards.abi,
```suggestion
	Rewards.abi
```

2021-04-10 05:27 UTC, bitcoinbrisbane commented on src/index.ts
> +  UPDATE_AMM_REWARD_INTERVAL: process.env.UPDATE_AMM_REWARD_INTERVAL,
Do we need this comma?
```suggestion
  UPDATE_AMM_REWARD_INTERVAL: process.env.UPDATE_AMM_REWARD_INTERVAL
```

2021-04-11 11:34 UTC, bitcoinbrisbane requested changes
Some suggestions

2021-04-12 00:37 UTC, mystbrent commented on src/tasks/UpdateAMMReward.ts
> +	Rewards.abi,
The dangling comma is not required but as far as I know I have been following this as part of JS best practices: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

Please let me know you're thoughts on this :)

2021-04-12 00:37 UTC, mystbrent commented on src/index.ts
> +  UPDATE_AMM_REWARD_INTERVAL: process.env.UPDATE_AMM_REWARD_INTERVAL,
The dangling comma is not required but as far as I know I have been following this as part of JS best practices: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

Please let me know you're thoughts on this :)

2021-04-16 09:35 UTC, ctverceles reviewed
@mystbrent This is working for me now locally but on kovan i get this:
![image](https://user-images.githubusercontent.com/16344192/115004195-232a5200-9ed9-11eb-93e9-9c872df7723a.png). Testing on kovan worked yesterday, I don't know if this is a Kovan network related thing. FYI @ernestpascual @schystz  if this looks familiar

2021-04-16 09:51 UTC, schystz commented
> @mystbrent This is working for me now locally but on kovan i get this:
> ![image](https://user-images.githubusercontent.com/16344192/115004195-232a5200-9ed9-11eb-93e9-9c872df7723a.png). Testing on kovan worked yesterday, I don't know if this is a Kovan network related thing. FYI @ernestpascual @schystz if this looks familiar

Yeah this looks like the same error when calling Rewards contract's write methods in Kovan.

2021-04-16 09:58 UTC, mystbrent commented
Thank you for spotting this guys @ctverceles @schystz. I have tested in my local and I do not have the error.

![](https://i.imgur.com/CRBe68Y.png)

2021-04-16 09:58 UTC, mystbrent commented
I'll do a root cause analysis for this

2021-04-16 10:06 UTC, ctverceles commented
> Thank you for spotting this guys @ctverceles @schystz. I have tested in my local and I do not have the error.
> 
> ![](https://camo.githubusercontent.com/fb7f85e012747201929055d6f49ecf8be85fa6170e143fe947e702dae533a90a/68747470733a2f2f692e696d6775722e636f6d2f435242653638592e706e67)

Yes local works fine for me as well, its kovan thats getting that weird err for me. I suspect its not cause of this repo but we have to find out why regardless

2021-04-19 02:10 UTC, ctverceles commented
Ok kovan working now! https://kovan.etherscan.io/address/0xAC0e7b9C0A2ed0c4420D163F64a1C6eF48459d0f @mystbrent

2021-04-19 02:38 UTC, ctverceles approved these changes

2021-04-19 03:47 UTC, merged